//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Halfox.LongDing
{
    using System;
    using System.Collections.Generic;
    
    public partial class longding_users
    {
        public long uid { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public string qq { get; set; }
        public string password { get; set; }
        public string paypassword { get; set; }
        public string salt { get; set; }
        public string nickname { get; set; }
        public string avatar { get; set; }
        public Nullable<sbyte> verifyemail { get; set; }
        public Nullable<sbyte> verifymobile { get; set; }
        public Nullable<sbyte> verifywenxin { get; set; }
        public Nullable<decimal> paycredits { get; set; }
        public Nullable<decimal> rankcredits { get; set; }
        public Nullable<long> parentid { get; set; }
        public Nullable<short> regionid { get; set; }
        public Nullable<short> typeid { get; set; }
        public string openid { get; set; }
        public string unionid { get; set; }
        public string lables { get; set; }
    }
}
